"""Single A2A seller agent entrypoint. Generated by `bag recipe code agent`.

This is the VALUABLE agent AND the SOLE key-holder/signer. It serves its two
ERC-8183 seller skills DIRECTLY over the A2A protocol on AWS Bedrock AgentCore
(``--protocol A2A``): AgentCore's ``serve_a2a`` wraps the official ``a2a-sdk`` and
exposes the agent card at ``/.well-known/agent-card.json`` + JSON-RPC
``message/send`` on ``0.0.0.0:9000`` (``AGENT_PORT`` overrides locally). There
is no separate forwarding service — the
agent IS the seller (see executor.py + agent_card.py).

A2A skills (executor.py):

    negotiate     → read the FIXED list price → CLAMP to [min,max] → EIP-191 SIGN
                    the offer (no LLM, no tools) → return the signed offer (or reject)
    notify_funded → re-verify the funded job on-chain (fast) → ACK accepted at once,
                    then in the BACKGROUND: LLM work → manifest → storage →
                    submit_result (SIGN + broadcast). The buyer polls the chain for
                    the deliverable. Each notify also sweeps other FUNDED jobs
                    (buyer-push fallback). While background work is in flight the
                    ``ping_handler`` reports HEALTHY_BUSY so AgentCore keeps the
                    scale-to-zero runtime warm until it lands.

Buyers reach this endpoint with an OAuth2 (Cognito) bearer — AgentCore A2A
mandates inbound auth (see agent_card.py + ``bag deploy provision-cognito``).

## Boundaries (do NOT cross — they are the whole point)

- The agent does ALL deterministic SIGNING (quote-sign + submit + settle +
  automatic x402 LLM-credit auto-renew). ALL signing is FIXED code in
  ``signing.py`` — NEVER an LLM-callable tool (money never in the LLM).
- The price is a FIXED list price from studio.toml (clamped before signing) —
  the LLM never prices; it only PRODUCES the work text in ``fulfill``.
- Chain access for the LLM is READ-ONLY tools only (``tools.py``).
- ``settle`` (claim payment after the dispute window) is operator-driven — run
  ``bag erc8183 settle <job_id>``; it is deliberately NOT an A2A skill.
"""
from __future__ import annotations

import json
import logging
import os
import sys

from google.adk.agents import Agent
from google.adk.runners import InMemoryRunner
from google.genai import types as gtypes

from managed_model import build_model
from bnbagent_studio_core.wallet import (
    ensure_keystore_materialized,
    ensure_twak_materialized,
)

import blockchain as pcs
from agent_card import build_agent_card
from executor import SellerAgentExecutor
from tools import LLM_READ_TOOLS

APP_NAME = "agent"


# --- Logging -------------------------------------------------------------------
# Make the agent's own logs visible in `docker logs` / CloudWatch — ESPECIALLY
# the BACKGROUND notify_funded delivery, which runs AFTER the A2A ack (off the
# request path). Without this the "seller-agent.*" loggers inherit the root
# config (which opentelemetry / AgentCore may leave at WARNING or route away),
# so a delivery that fails — e.g. a missing STORAGE_API_URL at the IPFS-pin step
# — vanishes silently while the buyer polls the chain forever. We attach our own
# stdout handler at INFO so success AND failure are always on stdout.
def _configure_logging() -> None:
    log = logging.getLogger("seller-agent")
    if log.handlers:  # idempotent (cold start may re-import)
        return
    handler = logging.StreamHandler(sys.stdout)
    handler.setFormatter(logging.Formatter("%(asctime)s %(levelname)s %(name)s: %(message)s"))
    log.addHandler(handler)
    log.setLevel(logging.INFO)
    log.propagate = False  # don't double-log via the root handler


_configure_logging()


def _generator_tag() -> str:
    """Deliverable ``generator`` label: this seller's own name, read from
    studio.toml ``[project].name`` (minus the ``-agent`` suffix) so each
    delivered manifest is self-identifying. Best-effort — falls back to
    ``APP_NAME`` if the config can't be read."""
    try:
        from bnbagent_studio_core import config

        name = str(((config.load_studio_toml() or {}).get("project") or {}).get("name") or "")
    except Exception:  # noqa: BLE001 — a metadata label must never break fulfill
        return APP_NAME
    return name[: -len("-agent")] if name.endswith("-agent") else (name or APP_NAME)


GENERATOR = _generator_tag()


# --- Runtime secrets -----------------------------------------------------------
# Keep plaintext secrets OUT of agentcore.json. When BNBAGENT_RUNTIME_SECRET_ID is set
# (deployed runtime), pull a JSON {ENV_NAME: value} blob from AWS Secrets Manager
# into the process env BEFORE anything reads it (keystore unlock, provider key,
# build_model, Cognito OAuth env). No-op locally, where .env.local already
# populated the environment — `setdefault` never overrides an already-present var.
def _load_runtime_secrets() -> None:
    secret_id = os.environ.get("BNBAGENT_RUNTIME_SECRET_ID")
    if not secret_id:
        return
    import boto3

    resp = boto3.client("secretsmanager").get_secret_value(SecretId=secret_id)
    for key, value in json.loads(resp["SecretString"]).items():
        os.environ.setdefault(key, str(value))


_load_runtime_secrets()

# --- Wallet bootstrap -----------------------------------------------------------
# Wallet material is NEVER bundled into the deploy artifact. `bag deploy`
# injects it via Secrets Manager and these calls (run once at cold start,
# before any signing) materialize it on disk. Each is a no-op for the other
# wallet kind and locally, where the wallet already lives on disk:
#  - evm-local: WALLET_KEYSTORE_JSON → keystore file (unlocked with WALLET_PASSWORD)
#  - twak:      TWAK_WALLET_JSON / TWAK_CREDENTIALS_JSON → $TMPDIR/twak-home/.twak
#               (exported as TWAK_HOME_DIR; twak reads TWAK_WALLET_PASSWORD itself)
ensure_keystore_materialized()
ensure_twak_materialized()

# --- Agent + runtime ----------------------------------------------------------
# LLM credit auto-renew (Pieverse path): `build_model()` (in managed_model.py)
# returns a managed model wrapper that auto-tops up the active Pieverse key
# before each generate call when [llm.auto_renew] is enabled. That top-up is
# the ONLY automatic signing path outside signing.py — it is budget-gated and
# is NOT an LLM tool. It rides transparently into `fulfill`.
#
# trap: Agent.name must be a valid Python identifier — no hyphens. ADK silently
# misbehaves on names containing "-".
#
# The LLM runs ONLY in `fulfill` (the value hook). `negotiate` is rule-based and
# never touches the LLM. The read-only chain tools are attached so the work can
# read on-chain context if it needs to — drop them from `tools.py` if your work
# doesn't read chain. Signing / settle are NEVER tools — they are fixed code in
# signing.py, triggered by the A2A skills, never callable by the LLM. (The one
# deliberate exception: the x402-buyer recipe's PAID fetch tools — see the
# `tools=` note below — the LLM picks the URL, but who gets paid and the
# per-call/daily caps stay locked in studio.toml.)
_model = build_model()  # managed model with the auto-renew hook (fulfill only)

agent = Agent(
    name="seller_agent",
    model=_model,
    instruction=(
        "You are a seller agent. You do the actual work once a job is funded. "
        "Be concrete and concise. Use the read-only chain tools when on-chain "
        "context helps. If a paid-data tool such as `buy_with_x402` is available "
        "to you, USE IT to fetch the data a task needs — those merchants (e.g. "
        "CoinMarketCap) charge via on-chain wallet payment, NOT an API key; never "
        "reply that you cannot complete the task for lack of an API key. "
        # Numeric discipline. Handed the raw status dict, this agent reported the
        # raw V3 liquidity integer as "TVL: 335,389.79 BNB" (real TVL: $0.81) and
        # invented pending-fee figures ~1e12 too large. For a paid status report
        # the numbers ARE the product, so they come from code, not from the model.
        "For ANY question about the LP position's status or economics, call "
        "`get_status_report` and quote its figures VERBATIM. Never compute, "
        "convert, round, or reformat a financial number yourself, and never state "
        "a figure you did not read from a tool result. `liquidity_raw` is V3 "
        "liquidity units — NOT a token amount and NOT a money value; the money "
        "figure is `tvl`. If a number is not in a tool result, say it is unavailable."
    ),
    # LLM_READ_TOOLS = read-only chain tools (wallet, balances, ERC-8004/8183
    # queries). Edit `tools.py` to add/remove. These are READ-ONLY — the agent
    # never signs via a tool; all signing is in signing.py (fixed code).
    # To let the agent BUY paid data at work time (e.g. CMC market data after
    # `bag x402 trust cmc` + `bag recipe code x402-buyer`), append the emitted
    # tool set — payee + per-call/daily caps stay locked in studio.toml:
    #   from x402_buyer import x402_buyer_set
    #   tools=[*LLM_READ_TOOLS, *x402_buyer_set],
    tools=LLM_READ_TOOLS,
)
runner = InMemoryRunner(agent=agent, app_name=APP_NAME)


# --- One-shot LLM helper (the executor's `fulfill` work hook) ------------------
async def _run_llm(prompt: str, *, session_id: str) -> str:
    """Run the agent once and return the concatenated final-response text.

    `fulfill` produces a single deliverable (not an SSE stream), so we collect
    the final response text. The session is created on the runner's own
    session_service (a separate InMemorySessionService would raise "Session not
    found" on run_async).
    """
    session_service = runner.session_service
    existing = await session_service.get_session(
        app_name=runner.app_name, user_id="service", session_id=session_id
    )
    if existing is None:
        await session_service.create_session(
            app_name=runner.app_name, user_id="service", session_id=session_id
        )

    user_msg = gtypes.Content(role="user", parts=[gtypes.Part(text=prompt)])
    parts: list[str] = []
    async for event in runner.run_async(
        user_id="service", session_id=session_id, new_message=user_msg
    ):
        if event.is_final_response() and event.content:
            for p in event.content.parts:
                if p.text:
                    parts.append(p.text)
    return "\n".join(parts).strip()


def _default_network() -> str:
    """The active network for the seller runtime (job lookups, funded sweep).

    Delegates to ``blockchain.default_network()`` rather than reading
    ``[network].default`` itself — the scaffold's version ignored
    ``$BNB_NETWORK``, so exporting mainnet moved the strategy while leaving the
    seller polling testnet jobs. That is B20 with a different blast radius: a
    second resolver for one fact will always drift from the first.
    """
    return pcs.default_network()


# --- A2A surface --------------------------------------------------------------
# The executor backs the seller skills with signing.py fixed code (NEVER an LLM
# tool). serve_a2a (AgentCore SDK, built on the official a2a-sdk) hosts the agent
# card + JSON-RPC message/send on 0.0.0.0:9000, adds GET /ping, and overwrites
# the card url with the deployed runtime URL ($AGENTCORE_RUNTIME_URL).
executor = SellerAgentExecutor(
    run_work=_run_llm, generator=GENERATOR, network=_default_network()
)
agent_card = build_agent_card()

# --- LP Monitor loop (spec 4.4) ------------------------------------------------
# The rebalancer is autonomous: a background thread polls the position and
# rebalances when the deterministic check says so. It only acts while
# [strategy] state is "active" (`python strategy.py activate`), so importing
# this module never starts moving funds on its own. The decision and the
# calldata are both fixed code — see strategy.py / lp_signing.py.
try:
    from blockchain import check_config_consistency
    from strategy import start_monitor

    # Loud at boot: cross-field config errors (wrong-chain currency, a token_id
    # from the other network) are invisible to per-field validation and only
    # surface as a signed-but-worthless quote or a trade against the wrong
    # position. Warn rather than exit so a config typo can't take the A2A
    # surface down.
    for _problem in check_config_consistency():
        logging.getLogger("seller-agent").error("CONFIG: %s", _problem)

    # EXACTLY ONE process in a deployment may run the loop, and it must be
    # chosen explicitly — hence opt-in rather than the default.
    #
    # `strategy._rebalance_lock` is an flock, which excludes a second process on
    # the SAME filesystem but cannot see one on another host. Split the seller
    # and the monitor across two machines with this defaulting to on and both
    # take the lock, both read the same liquidity, and both rebalance — the B11
    # race again, with the guard structurally unable to fire.
    #
    # Defaulting off trades a loud, harmless failure (no loop; visible in the
    # logs below, in /health, and in `is_monitor_running()`) for a silent,
    # expensive one. The service layer's mirror switch is $SERVICE_RUN_MONITOR.
    if os.environ.get("AGENT_RUN_MONITOR") == "1":
        start_monitor()
        logging.getLogger("seller-agent").info(
            "LP monitor started here (AGENT_RUN_MONITOR=1)")
    else:
        logging.getLogger("seller-agent").info(
            "LP monitor NOT started here: set AGENT_RUN_MONITOR=1 to run it in "
            "this process, or SERVICE_RUN_MONITOR=1 to run it in the service "
            "layer. Exactly one of the two, and never on two hosts at once.")
except Exception as exc:  # noqa: BLE001 — the A2A surface must serve regardless
    logging.getLogger("seller-agent").warning("LP monitor not started: %s", exc)


def _ping_status():
    """GET /ping status fed to AgentCore: HEALTHY_BUSY while a background delivery
    is in flight, else HEALTHY.

    notify_funded acks immediately and runs the slow work (LLM + on-chain submit)
    in the background. Reporting HEALTHY_BUSY tells AgentCore the runtime is still
    working, so the scale-to-zero runtime is NOT reaped on idle before delivery
    lands (bounded by the session max-lifetime; ≤8h)."""
    from bedrock_agentcore.runtime.models import PingStatus

    return PingStatus.HEALTHY_BUSY if executor.is_busy() else PingStatus.HEALTHY


# --- JSON-RPC error hardening -------------------------------------------------
# a2a-sdk builds -32602 (InvalidParams) / -32600 (InvalidRequest) JSON-RPC error
# responses from a Pydantic ValidationError, and Pydantic embeds an ``input`` key
# in each error entry that echoes the caller's raw request body back to them
# (a2a/server/apps/jsonrpc/jsonrpc_app.py). It only ever reflects the CALLER'S OWN
# input to that same caller (not cross-tenant), so this is low-severity, but we
# strip ``input`` from outgoing JSON-RPC error data anyway — no reason to echo
# request bodies. This is a tiny pure-ASGI wrapper (no SDK edit) that rewrites the
# response body only for JSON-RPC error payloads; every other response passes
# through untouched.
def _mount_deliverable_route(app) -> None:
    """Serve the deliverable at the URL ``submit`` already published on-chain.

    B23. ``submit_result`` uploads the manifest to local storage, then publishes
    ``{ERC8183_AGENT_URL}/job/{id}/response`` on-chain because a ``file://`` URL
    is not fetchable by a buyer. But ``serve_a2a`` mounts only the card, /ping
    and JSON-RPC — nothing serves that path, so the seller 404'd its own
    advertised URL and a buyer who had paid could not collect. The manifest was
    on disk the whole time; only the route was missing.

    The prefix comes from ``ERC8183_AGENT_URL`` so the route and the published
    URL cannot drift apart — they are derived from one value.

    Public by design: the URL is published on-chain, and the manifest is what
    the buyer paid for. It carries no key material.
    """
    import json as _json
    from pathlib import Path
    from urllib.parse import urlparse

    from starlette.responses import JSONResponse
    from starlette.routing import Route

    log = logging.getLogger("seller-agent")
    agent_url = os.environ.get("ERC8183_AGENT_URL")
    if not agent_url:
        log.warning(
            "ERC8183_AGENT_URL unset — not mounting the deliverable route. "
            "submit will then publish a file:// URL no buyer can fetch."
        )
        return

    prefix = urlparse(agent_url).path.rstrip("/")
    # Same default the SDK's LocalStorageProvider.from_env uses.
    store = Path(os.environ.get("STORAGE_LOCAL_PATH") or ".agent-data")

    async def _deliverable(request):
        try:
            # int() is also the path-traversal guard: the id is the filename.
            job_id = int(request.path_params["job_id"])
        except (TypeError, ValueError):
            return JSONResponse({"error": "job_id must be an integer"}, status_code=400)
        path = store / f"erc8183-job-{job_id}.json"
        if not path.exists():
            return JSONResponse(
                {"error": f"no deliverable stored for job {job_id}",
                 "hint": "this seller only serves jobs it submitted itself"},
                status_code=404,
            )
        return JSONResponse(_json.loads(path.read_text()))

    app.router.routes.append(
        Route(f"{prefix}/job/{{job_id}}/response", _deliverable, methods=["GET"])
    )
    log.info("deliverable route mounted at %s/job/{job_id}/response (store=%s)",
             prefix, store.resolve())


def _strip_error_input(app):
    async def _wrapped(scope, receive, send):
        if scope["type"] != "http":
            await app(scope, receive, send)
            return

        # `buffer` is decided from the response start (content-type): we only
        # buffer+rewrite JSON bodies (the JSON-RPC error path). SSE / any other
        # response streams through unbuffered so streaming is never broken.
        state: dict = {"buffer": False, "start": None}
        chunks: list[bytes] = []

        async def _capture(message):
            if message["type"] == "http.response.start":
                ctype = dict(message.get("headers", [])).get(b"content-type", b"")
                state["buffer"] = b"application/json" in ctype.lower()
                state["start"] = message
                if not state["buffer"]:
                    await send(message)
            elif message["type"] == "http.response.body":
                if not state["buffer"]:
                    await send(message)
                    return
                chunks.append(message.get("body", b"") or b"")
                if message.get("more_body"):
                    return
                await _emit(send, state["start"], b"".join(chunks))
            else:
                await send(message)

        await app(scope, receive, _capture)

    return _wrapped


async def _emit(send, start_message, body: bytes):
    new_body = body
    try:
        payload = json.loads(body)
        # JSON-RPC error: {"jsonrpc": "2.0", "error": {"data": [ {...,"input":..}]}}
        data = payload.get("error", {}).get("data")
        if isinstance(data, list) and any(
            isinstance(e, dict) and "input" in e for e in data
        ):
            for e in data:
                if isinstance(e, dict):
                    e.pop("input", None)
            new_body = json.dumps(payload).encode("utf-8")
    except Exception:  # noqa: BLE001 — never let hardening break a response
        new_body = body

    if start_message is not None:
        headers = [
            (k, v)
            for (k, v) in start_message.get("headers", [])
            if k.lower() != b"content-length"
        ]
        headers.append((b"content-length", str(len(new_body)).encode("latin-1")))
        start_message = {**start_message, "headers": headers}
        await send(start_message)
    await send({"type": "http.response.body", "body": new_body, "more_body": False})


if __name__ == "__main__":
    import uvicorn
    from bedrock_agentcore.runtime import build_a2a_app

    # build_a2a_app is serve_a2a's own builder (it returns the Starlette app
    # instead of running uvicorn), so the /ping + card + JSON-RPC wiring is
    # identical to serve_a2a — we only interpose the error-input stripper before
    # serving.
    app = build_a2a_app(executor, agent_card, ping_handler=_ping_status)
    # Before the wrapper: _strip_error_input returns a bare ASGI callable with
    # no router to append to.
    _mount_deliverable_route(app)
    app = _strip_error_input(app)

    uvicorn.run(
        app,
        # AgentCore's A2A contract is 0.0.0.0:9000. Do not honor the HTTP
        # protocol's $PORT=8080 convention here; AGENT_PORT is the local-dev /
        # rendered-container override.
        host=os.environ.get("AGENT_BIND_HOST") or "0.0.0.0",
        port=int(os.environ.get("AGENT_PORT") or "9000"),
        log_level="info",
    )
